
// auth action types
export const LOGIN_START = 'LOGINT_START';
export const LOGIN_SUCCESS = 'LOGINT_SUCCESS';
export const LOGIN_ERROR = 'LOGINT_END';

export const SIGNUP_START = 'SIGNUP_START';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';


export const AUTHENTICATED_USER = 'AUTHENTICATED_USER';
export const LOGOUT = 'LOGOUT';

export const UPDATE_PROFILE_START = 'UPDATE_PROFILE_START';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILED = 'UPDATE_PROFILE_FAILED';

export const USER_PROFILE_LOADING = 'USER_PROFILE_LOADING';
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS';
export const USER_PROFILE_FAILED = 'USER_PROFILE_FAILED';

export const GET_POST_LOADING = 'GET_POST_LOADING';
export const GET_POST_SUCCESS = 'GET_POST_SUCCESS';
export const GET_POST_FAILED = 'GET_POST_FAILED';
export const UPLOAD_POST_LOADING = 'UPLOAD_POST_LOADING';
export const UPLOAD_POST_SUCCESS = 'UPLOAD_POST_SUCCESS';
export const UPLOAD_POST_FAILED = 'UPLOAD_POST_FAILED';
export const DELETE_POST_LOADING = 'DELETE_POST_LOADING';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
export const DELETE_POST_FAILED = 'DELETE_POST_FAILED';

export const ADD_FRIEND_REQUEST = 'ADD_FRIEND_REQUEST';
export const ADD_FRIEND_SUCCESS = 'ADD_FRIEND_SUCCESS';
export const ADD_FRIEND_FAILED = 'ADD_FRIEND_FAILED';
export const REMOVE_FRIEND_LOAD = 'REMOVE_FRIEND_LOAD';
export const REMOVE_FRIEND_SUCCESS = 'REMOVE_FRIEND_SUCCESS';
export const REMOVE_FRIEND_FAILED = 'REMOVE_FRIEND_FAILED';

// create comments 
export const CREATE_COMMENT_LOAD = 'CREATE_COMMENT_LOAD';
export const CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS';
export const CREATE_COMMENT_FAIL = 'CREATE_COMMENT_FAIL';

// create likes
export const CREATE_LIKES_LOAD = 'CREATE_LIKES_LOAD';
export const CREATE_LIKES_SUCCESS = 'CREATE_LIKES_SUCCESS';
export const CREATE_LIKES_FAILED = 'CREATE_LIKES_FAILED';
